apiVersion: v1
kind: Service
metadata:
  name: devops-api-service
  namespace: devops-api
spec:
  selector:
    app: devops-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: devops-api-loadbalancer
  namespace: devops-api
spec:
  selector:
    app: devops-api
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer